spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true  # Enabling H2 console
      path: /h2-console  # URL path to access H2 console
      settings:
        web-allow-others: true

  # multipart file properties
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB